"""The static demo artifact stays in sync with its sources (pure string build)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def test_demo_html_is_current_build():
    result = subprocess.run(
        [sys.executable, "scripts/build_demo.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_demo_embeds_mock_ahead_of_app_script():
    demo = (ROOT / "docs" / "index.html").read_text(encoding="utf-8")
    assert demo.count("demo-mock.js — offline demo layer") == 1
    assert "GENERATED by scripts/build_demo.py" in demo
    # The mock must precede the application script so window.fetch is
    # overridden before the first request fires.
    assert demo.index("demo-mock.js — offline demo layer") < demo.rindex("<script>")
