#!/usr/bin/env python3
"""Bake the static click-through demo: ui/index.html + ui/demo-mock.js -> docs/index.html.

The mock layer overrides window.fetch inside the page and serves canned
responses for every endpoint the app calls, so the demo runs on
GitHub Pages (or a local file) with no backend and no external requests. The
build is a deterministic pure-string operation: the mock script block is
injected verbatim directly ahead of the application's main <script> block.

Usage:
    python scripts/build_demo.py            # (re)write docs/index.html
    python scripts/build_demo.py --check    # exit 1 if docs/index.html is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UI = ROOT / "ui" / "index.html"
MOCK = ROOT / "ui" / "demo-mock.js"
OUT = ROOT / "docs" / "index.html"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/build_demo.py — do not edit. "
    "Edit ui/index.html / ui/demo-mock.js and rebuild. -->\n"
)


def build() -> str:
    html = UI.read_text(encoding="utf-8")
    mock = MOCK.read_text(encoding="utf-8")
    if "</script" in mock:
        raise SystemExit("demo-mock.js must not contain a closing script tag")
    # Inject ahead of the application script — the last <script> block in the page.
    at = html.rindex("<script>")
    html = html[:at] + "<script>\n" + mock + "</script>\n\n" + html[at:]
    # Mark the artifact as generated, directly after the doctype.
    doctype_end = html.index("\n") + 1
    return html[:doctype_end] + GENERATED_NOTE + html[doctype_end:]


def main(argv: list[str]) -> int:
    built = build()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != built:
            print(f"{OUT.relative_to(ROOT)} is stale — run: python scripts/build_demo.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.write_text(built, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(built):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
